set_save_state_version(1)
set_area_name("river_town")
set_milestone_complete("ant_tracks", true)
set_milestone_complete("castle_bird", true)
set_milestone_complete("heading_west_guards", true)
set_milestone_complete("river_town_intro", true)
set_saved_players("egbert", "frogbert")
set_elapsed_time(183.712000)
set_cash(102)
add_crystals(0)
set_name(0, "egbert")
set_attributes(0, 7, 10, 5, 5, 1, 0, 42)
set_weapon(0, "STICK")
set_armor(0, "")
set_accessory(0, "")
set_crystals(0, 0, 0, 0, 0, 0)
set_selected_abilities(0, "USE", "ATTACK", "", "JUMP")
set_name(1, "frogbert")
set_attributes(1, 5, 10, 5, 5, 1, 0, 42)
set_weapon(1, "SHOVEL")
set_armor(1, "")
set_accessory(1, "")
set_crystals(1, 0, 0, 0, 0, 0)
set_selected_abilities(1, "USE", "ATTACK", "", "JUMP")
set_name(2, "bisou")
set_attributes(2, 10, 10, 5, 5, 1, 0, 42)
set_weapon(2, "BOW")
set_armor(2, "")
set_accessory(2, "")
set_crystals(2, 0, 0, 0, 0, 0)
set_selected_abilities(2, "USE", "ATTACK", "", "JUMP")
restore_item(SAVE_PLAYER, 2, 1226.000000, 279.000000)
