set_save_state_version(1)
set_area_name("map:STONE_CRATER")
set_milestone_complete("ant_tracks", true)
set_milestone_complete("antcolony_chest1", true)
set_milestone_complete("antcolony_chest2", true)
set_milestone_complete("ants_chest4", true)
set_milestone_complete("ants_crystal1", true)
set_milestone_complete("ants_crystal2", true)
set_milestone_complete("bisou_crystal", true)
set_milestone_complete("canoe_outro", true)
set_milestone_complete("castle_bird", true)
set_milestone_complete("entered_old_forest", true)
set_milestone_complete("exited_river_town_south", true)
set_milestone_complete("first_amaysa_encounter", true)
set_milestone_complete("flea_intro", true)
set_milestone_complete("heading_west_guards", true)
set_milestone_complete("jump_switch_info", true)
set_milestone_complete("learned_chop", true)
set_milestone_complete("left_pyou_area", true)
set_milestone_complete("of2_chest1", true)
set_milestone_complete("of_chest1", true)
set_milestone_complete("of_chest2", true)
set_milestone_complete("of_chest3", true)
set_milestone_complete("of_chest4", true)
set_milestone_complete("of_chest5", true)
set_milestone_complete("old_oak_battle", true)
set_milestone_complete("oldoak_crystal1", true)
set_milestone_complete("oldoak_crystal2", true)
set_milestone_complete("oldoak_crystal3", true)
set_milestone_complete("pyou2_chest1", true)
set_milestone_complete("pyou_crystal", true)
set_milestone_complete("pyou_intro", true)
set_milestone_complete("pyoudock_intro", true)
set_milestone_complete("river_town_intro", true)
set_saved_players("egbert", "frogbert", "bisou")
set_elapsed_time(2508.935982)
set_cash(51)
add_crystals(0)
give_items("HEALTHVIAL", 1)
give_items("DIRTYSOCK", 1)
give_equipment(WEAPON, "STICK", 1)
give_equipment(WEAPON, "SHOVEL", 1)
give_equipment(WEAPON, "BAT", 1)
set_name(0, "egbert")
set_attributes(0, 10, 20, 5, 5, 1, 0, 42)
set_status(0, "")
set_weapon(0, "CLEAVER")
set_armor(0, "")
set_accessory(0, "GLOVES")
set_crystals(0, 0, 0, 1, 1, 0)
set_selected_abilities(0, "USE", "ATTACK", "", "JUMP")
set_name(1, "frogbert")
set_attributes(1, 10, 20, 5, 5, 1, 0, 42)
set_status(1, "")
set_weapon(1, "RAKE")
set_armor(1, "COVERALLS")
set_accessory(1, "")
set_crystals(1, 1, 0, 0, 1, 0)
set_selected_abilities(1, "USE", "ATTACK", "KICK", "JUMP")
set_name(2, "bisou")
set_attributes(2, 9, 20, 5, 5, 1, 0, 42)
set_status(2, "")
set_weapon(2, "BOW")
set_armor(2, "SHIRT")
set_accessory(2, "")
set_crystals(2, 0, 0, 1, 1, 0)
set_selected_abilities(2, "USE", "ATTACK", "", "JUMP")
