set_save_state_version(1)
set_area_name("caverns1")
set_milestone_complete("CAVERNS_INTRO", true)
set_milestone_complete("STONECRATER_BIGHOLE", true)
set_milestone_complete("ant_tracks", true)
set_milestone_complete("antcolony_chest1", true)
set_milestone_complete("antcolony_chest2", true)
set_milestone_complete("ants_chest1", true)
set_milestone_complete("ants_chest2", true)
set_milestone_complete("ants_chest4", true)
set_milestone_complete("ants_crystal1", true)
set_milestone_complete("ants_crystal2", true)
set_milestone_complete("bisou_crystal", true)
set_milestone_complete("canoe_outro", true)
set_milestone_complete("castle_banquet_hockeymask", true)
set_milestone_complete("castle_bird", true)
set_milestone_complete("castle_crystal_cash", true)
set_milestone_complete("castle_hall_sock", true)
set_milestone_complete("castle_tower3_chest1", true)
set_milestone_complete("castle_tower3_chest2", true)
set_milestone_complete("entered_old_forest", true)
set_milestone_complete("exited_river_town_south", true)
set_milestone_complete("first_amaysa_encounter", true)
set_milestone_complete("flea_intro", true)
set_milestone_complete("frogbert_chest", true)
set_milestone_complete("heading_west_guards", true)
set_milestone_complete("inn_bed_chest", true)
set_milestone_complete("jump_switch_info", true)
set_milestone_complete("learned_chop", true)
set_milestone_complete("left_pyou_area", true)
set_milestone_complete("mill_chest", true)
set_milestone_complete("of2_chest1", true)
set_milestone_complete("of_chest1", true)
set_milestone_complete("of_chest2", true)
set_milestone_complete("of_chest3", true)
set_milestone_complete("of_chest4", true)
set_milestone_complete("of_chest5", true)
set_milestone_complete("old_oak_battle", true)
set_milestone_complete("oldoak_crystal1", true)
set_milestone_complete("oldoak_crystal2", true)
set_milestone_complete("oldoak_crystal3", true)
set_milestone_complete("pyou2_chest1", true)
set_milestone_complete("pyou2_chest3", true)
set_milestone_complete("pyou_chest", true)
set_milestone_complete("pyou_crystal", true)
set_milestone_complete("pyou_intro", true)
set_milestone_complete("pyoudock_intro", true)
set_milestone_complete("r1_chest", true)
set_milestone_complete("r3_chest", true)
set_milestone_complete("river_town_intro", true)
set_milestone_complete("sc_boulder1", true)
set_milestone_complete("sc_boulder2", true)
set_milestone_complete("sc_boulder3", true)
set_milestone_complete("sc_boulder4", true)
set_milestone_complete("stone_crater_amaysa_scene", true)
set_milestone_complete("stone_crater_boulder_pushed", true)
set_milestone_complete("stonecrater1_chest1", true)
set_milestone_complete("stonecrater2.5_chest1", true)
set_milestone_complete("stonecrater2.5_chest2", true)
set_milestone_complete("stonecrater2.5_chest4", true)
set_milestone_complete("stonecrater2_chest1", true)
set_milestone_complete("stonecrater2_chest2", true)
set_milestone_complete("stonecrater2_chest3", true)
set_milestone_complete("stonecrater4_chest1", true)
set_milestone_complete("whack_a_skunk_sock", true)
set_saved_players("frogbert", "bisou", "egbert")
set_elapsed_time(3986.000000)
set_cash(34)
add_crystals(1)
give_items("HEALTHVIAL", 10)
give_items("DIRTYSOCK", 3)
give_items("ANTIDOTE", 3)
give_items("MAGICJAR", 1)
give_items("HEALTHJAR", 1)
give_equipment(WEAPON, "RAKE", 1)
give_equipment(ACCESSORY, "SOMBRERO", 1)
give_equipment(ACCESSORY, "REDRING", 1)
set_name(0, "frogbert")
set_attributes(0, 13, 20, 5, 5, 1, 0, 42)
set_status(0, "")
set_weapon(0, "SLEDGEHAMMER")
set_armor(0, "SHIRT")
set_accessory(0, "HOCKEYMASK")
set_crystals(0, 0, 0, 0, 1, 0)
set_selected_abilities(0, "USE", "ATTACK", "", "JUMP")
set_name(1, "bisou")
set_attributes(1, 22, 20, 5, 5, 1, 0, 42)
set_status(1, "")
set_weapon(1, "BOW")
set_armor(1, "COVERALLS")
set_accessory(1, "BOOTS")
set_crystals(1, 0, 1, 1, 1, 0)
set_selected_abilities(1, "BURROW", "ATTACK", "HEAL", "JUMP")
set_name(2, "egbert")
set_attributes(2, 10, 20, 5, 5, 1, 0, 42)
set_status(2, "")
set_weapon(2, "CLEAVER")
set_armor(2, "BOX")
set_accessory(2, "GLOVES")
set_crystals(2, 0, 0, 0, 1, 0)
set_selected_abilities(2, "USE", "ATTACK", "", "JUMP")
restore_item(SAVE_PLAYER, 2, 440.000000, 168.000000)
