set_save_state_version(1)
set_area_name("caverns7")
set_milestone_complete("CAVERNS_INTRO", true)
set_milestone_complete("STONECRATER_BIGHOLE", true)
set_milestone_complete("ant_tracks", true)
set_milestone_complete("antcolony_chest1", true)
set_milestone_complete("antcolony_chest2", true)
set_milestone_complete("ants_chest1", true)
set_milestone_complete("ants_chest2", true)
set_milestone_complete("ants_chest4", true)
set_milestone_complete("ants_crystal1", true)
set_milestone_complete("ants_crystal2", true)
set_milestone_complete("bisou_crystal", true)
set_milestone_complete("canoe_outro", true)
set_milestone_complete("castle_banquet_hockeymask", true)
set_milestone_complete("castle_bird", true)
set_milestone_complete("castle_crystal_cash", true)
set_milestone_complete("castle_hall_sock", true)
set_milestone_complete("castle_tower3_chest1", true)
set_milestone_complete("castle_tower3_chest2", true)
set_milestone_complete("caverns2_chest2", true)
set_milestone_complete("chest_puzzle", true)
set_milestone_complete("entered_old_forest", true)
set_milestone_complete("exited_river_town_south", true)
set_milestone_complete("first_amaysa_encounter", true)
set_milestone_complete("flea_intro", true)
set_milestone_complete("frogbert_chest", true)
set_milestone_complete("heading_west_guards", true)
set_milestone_complete("inn_bed_chest", true)
set_milestone_complete("jump_switch_info", true)
set_milestone_complete("learned_chop", true)
set_milestone_complete("left_pyou_area", true)
set_milestone_complete("mill_chest", true)
set_milestone_complete("of2_chest1", true)
set_milestone_complete("of_chest1", true)
set_milestone_complete("of_chest2", true)
set_milestone_complete("of_chest3", true)
set_milestone_complete("of_chest4", true)
set_milestone_complete("of_chest5", true)
set_milestone_complete("old_oak_battle", true)
set_milestone_complete("oldoak_crystal1", true)
set_milestone_complete("oldoak_crystal2", true)
set_milestone_complete("oldoak_crystal3", true)
set_milestone_complete("oldoak_crystal4", true)
set_milestone_complete("oldoak_crystal5", true)
set_milestone_complete("oldoak_crystal6", true)
set_milestone_complete("oldoak_crystal7", true)
set_milestone_complete("oldoak_crystal8", true)
set_milestone_complete("pyou2_chest1", true)
set_milestone_complete("pyou2_chest3", true)
set_milestone_complete("pyou_chest", true)
set_milestone_complete("pyou_crystal", true)
set_milestone_complete("pyou_intro", true)
set_milestone_complete("pyoudock_intro", true)
set_milestone_complete("r1_chest", true)
set_milestone_complete("r3_chest", true)
set_milestone_complete("river_town_intro", true)
set_milestone_complete("sc_boulder1", true)
set_milestone_complete("sc_boulder2", true)
set_milestone_complete("sc_boulder3", true)
set_milestone_complete("sc_boulder4", true)
set_milestone_complete("stone_crater_amaysa_scene", true)
set_milestone_complete("stone_crater_boulder_pushed", true)
set_milestone_complete("stonecrater1_chest1", true)
set_milestone_complete("stonecrater2.5_chest1", true)
set_milestone_complete("stonecrater2.5_chest2", true)
set_milestone_complete("stonecrater2.5_chest3", true)
set_milestone_complete("stonecrater2.5_chest4", true)
set_milestone_complete("stonecrater2_chest1", true)
set_milestone_complete("stonecrater2_chest2", true)
set_milestone_complete("stonecrater2_chest3", true)
set_milestone_complete("stonecrater4_chest1", true)
set_milestone_complete("whack_a_skunk_sock", true)
set_saved_players("egbert", "frogbert", "bisou")
set_elapsed_time(3767.696000)
set_cash(210)
add_crystals(0)
give_items("HEALTHVIAL", 11)
give_items("HEALTHJAR", 2)
give_items("DIRTYSOCK", 6)
give_items("ANTIDOTE", 9)
give_items("MAGICJAR", 1)
give_equipment(WEAPON, "STICK", 1)
give_equipment(WEAPON, "SHOVEL", 1)
give_equipment(WEAPON, "BAT", 1)
give_equipment(WEAPON, "RAKE", 1)
give_equipment(ACCESSORY, "REDRING", 1)
set_name(0, "egbert")
set_attributes(0, 13, 20, 6, 10, 1, 0, 42)
set_status(0, "")
set_weapon(0, "CLEAVER")
set_armor(0, "BOX")
set_accessory(0, "GLOVES")
set_crystals(0, 1, 1, 1, 1, 1)
set_selected_abilities(0, "USE", "ATTACK", "THROW", "JUMP")
set_name(1, "frogbert")
set_attributes(1, 19, 20, 9, 10, 1, 0, 42)
set_status(1, "")
set_weapon(1, "SLEDGEHAMMER")
set_armor(1, "SHIRT")
set_accessory(1, "HOCKEYMASK")
set_crystals(1, 1, 0, 1, 1, 1)
set_selected_abilities(1, "KICK", "ATTACK", "FIRE", "JUMP")
set_name(2, "bisou")
set_attributes(2, 13, 20, 10, 10, 1, 0, 42)
set_status(2, "")
set_weapon(2, "BOW")
set_armor(2, "COVERALLS")
set_accessory(2, "BOOTS")
set_crystals(2, 0, 0, 1, 1, 1)
set_selected_abilities(2, "USE", "ATTACK", "HEAL", "JUMP")
restore_item(SAVE_PLAYER, 3, 602.934692, 1012.580688)
