set_save_state_version(1)
set_area_name("stonecrater3")
set_milestone_complete("ant_tracks", true)
set_milestone_complete("antcolony_chest1", true)
set_milestone_complete("antcolony_chest2", true)
set_milestone_complete("ants_chest4", true)
set_milestone_complete("ants_crystal1", true)
set_milestone_complete("ants_crystal2", true)
set_milestone_complete("bisou_crystal", true)
set_milestone_complete("canoe_outro", true)
set_milestone_complete("castle_bird", true)
set_milestone_complete("entered_old_forest", true)
set_milestone_complete("exited_river_town_south", true)
set_milestone_complete("first_amaysa_encounter", true)
set_milestone_complete("flea_intro", true)
set_milestone_complete("heading_west_guards", true)
set_milestone_complete("jump_switch_info", true)
set_milestone_complete("learned_chop", true)
set_milestone_complete("left_pyou_area", true)
set_milestone_complete("of2_chest1", true)
set_milestone_complete("of_chest1", true)
set_milestone_complete("of_chest2", true)
set_milestone_complete("of_chest3", true)
set_milestone_complete("of_chest4", true)
set_milestone_complete("of_chest5", true)
set_milestone_complete("old_oak_battle", true)
set_milestone_complete("oldoak_crystal1", true)
set_milestone_complete("oldoak_crystal2", true)
set_milestone_complete("oldoak_crystal3", true)
set_milestone_complete("pyou2_chest1", true)
set_milestone_complete("pyou_crystal", true)
set_milestone_complete("pyou_intro", true)
set_milestone_complete("pyoudock_intro", true)
set_milestone_complete("river_town_intro", true)
set_milestone_complete("stonecrater1_chest1", true)
set_milestone_complete("stonecrater2_chest1", true)
set_milestone_complete("stonecrater2_chest2", true)
set_milestone_complete("stonecrater2_chest3", true)
set_milestone_complete("stonecrater3_chest1", true)
set_saved_players("frogbert", "bisou", "egbert")
set_elapsed_time(2833.383982)
set_cash(52)
add_crystals(0)
give_items("HEALTHVIAL", 9)
give_items("DIRTYSOCK", 2)
give_items("ANTIDOTE", 5)
give_equipment(WEAPON, "STICK", 1)
give_equipment(WEAPON, "SHOVEL", 1)
give_equipment(WEAPON, "BAT", 1)
give_equipment(WEAPON, "RAKE", 1)
set_name(0, "frogbert")
set_attributes(0, 12, 20, 5, 5, 1, 0, 42)
set_status(0, "")
set_weapon(0, "SLEDGEHAMMER")
set_armor(0, "COVERALLS")
set_accessory(0, "")
set_crystals(0, 1, 0, 0, 1, 0)
set_selected_abilities(0, "USE", "ATTACK", "KICK", "JUMP")
set_name(1, "bisou")
set_attributes(1, 13, 20, 5, 5, 1, 0, 42)
set_status(1, "")
set_weapon(1, "BOW")
set_armor(1, "SHIRT")
set_accessory(1, "BOOTS")
set_crystals(1, 0, 0, 1, 1, 0)
set_selected_abilities(1, "USE", "ATTACK", "", "JUMP")
set_name(2, "egbert")
set_attributes(2, 7, 20, 5, 5, 1, 0, 42)
set_status(2, "")
set_weapon(2, "CLEAVER")
set_armor(2, "")
set_accessory(2, "GLOVES")
set_crystals(2, 0, 0, 1, 1, 0)
set_selected_abilities(2, "USE", "ATTACK", "", "JUMP")
restore_item(SAVE_PLAYER, 2, 532.457458, 190.083862)
restore_item(SAVE_ENEMY, "stonecrater1", "stonecrater", 2, 344.000000, 140.002213, "armadillo", 3, "armadillo", "bazooka_ant", "armadillo")
restore_item(SAVE_ENEMY, "stonecrater1", "stonecrater", 2, 353.500000, 219.000000, "machete_ant", 3, "machete_ant", "scorpion", "bazooka_ant")
