#ifndef SPEECH_TYPES_H
#define SPEECH_TYPES_H

enum Speech_Type {
	SPEECH_NORMAL,
	SPEECH_THOUGHTS,
	SPEECH_SPECIAL,
	SPEECH_COLORED,
	SPEECH_COLORED_ROUNDED
};

enum Speech_Location {
	SPEECH_LOC_TOP,
	SPEECH_LOC_BOTTOM,
	SPEECH_LOC_ANY,
	SPEECH_LOC_FORCE_TOP,
	SPEECH_LOC_FORCE_BOTTOM
};

#endif
